package assignment_Handling_Alert;

import java.util.List;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

public class Handling_Multiple_Alert {

	public static void main(String[] args) throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://demo.guru99.com/test/simple_context_menu.html");
		
		//Creating object of actions class to perform mouse actions
		Actions action = new Actions(driver);
		WebElement button = driver.findElement(By.xpath("//span[text()='right click me']"));
		
		List<WebElement> list = driver.findElements(By.xpath("//ul[@class='context-menu-list context-menu-root']/li[contains(@class,'context-menu-item context-menu-icon')]"));
		
		//Performing actions on alert generated by each WebElement
		for (WebElement element : list) {
			action.contextClick(button).perform();
			element.click();
			Alert alert = driver.switchTo().alert();
			String message = alert.getText();
			System.out.println(message);
			alert.accept();
			Thread.sleep(2000);
		}
		driver.quit();
	}
}
